import "dotenv/config";
import { Pool } from "pg";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client.js";

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

type P = { title: string; topic: string; difficulty: string; points: number; description: string; constraints: string; testCases: { input: string; output: string; isHidden: boolean }[] };

const problems: P[] = [
  // Arrays (3)
  { title: "Search in Rotated Sorted Array", topic: "Arrays", difficulty: "MEDIUM", points: 200, description: "Given a rotated sorted array `nums` and a `target`, return the index of target or -1 if not found. Algorithm must be O(log n).", constraints: "1 <= nums.length <= 5000\n-10^4 <= nums[i] <= 10^4", testCases: [{ input: "[4,5,6,7,0,1,2]\n0", output: "4", isHidden: false }, { input: "[4,5,6,7,0,1,2]\n3", output: "-1", isHidden: false }, { input: "[1]\n0", output: "-1", isHidden: true }] },
  { title: "Find Minimum in Rotated Sorted Array", topic: "Arrays", difficulty: "MEDIUM", points: 200, description: "Given a sorted rotated array of unique elements, return the minimum element. Algorithm must run in O(log n).", constraints: "1 <= nums.length <= 5000\n-5000 <= nums[i] <= 5000", testCases: [{ input: "[3,4,5,1,2]", output: "1", isHidden: false }, { input: "[4,5,6,7,0,1,2]", output: "0", isHidden: false }, { input: "[11,13,15,17]", output: "11", isHidden: true }] },
  { title: "Largest Rectangle in Histogram", topic: "Arrays", difficulty: "HARD", points: 350, description: "Given an array of integers `heights` representing the histogram's bar heights where the width of each bar is 1, return the area of the largest rectangle in the histogram.", constraints: "1 <= heights.length <= 10^5\n0 <= heights[i] <= 10^4", testCases: [{ input: "[2,1,5,6,2,3]", output: "10", isHidden: false }, { input: "[2,4]", output: "4", isHidden: false }, { input: "[1]", output: "1", isHidden: true }] },
  // Strings (3)
  { title: "Zigzag Conversion", topic: "Strings", difficulty: "MEDIUM", points: 200, description: "The string 'PAYPALISHIRING' is written in a zigzag pattern on a given number of rows. Write the code that will take a string and make this conversion given a number of rows.", constraints: "1 <= s.length <= 1000\n1 <= numRows <= 1000", testCases: [{ input: "PAYPALISHIRING\n3", output: "PAHNAPLSIIGYIR", isHidden: false }, { input: "PAYPALISHIRING\n4", output: "PINALSIGYAHRPI", isHidden: false }, { input: "A\n1", output: "A", isHidden: true }] },
  { title: "Implement strStr()", topic: "Strings", difficulty: "EASY", points: 100, description: "Return the index of the first occurrence of `needle` in `haystack`, or -1 if `needle` is not part of `haystack`.", constraints: "1 <= haystack.length, needle.length <= 10^4", testCases: [{ input: "sadbutsad\nsad", output: "0", isHidden: false }, { input: "leetcode\nleeto", output: "-1", isHidden: false }, { input: "hello\nll", output: "2", isHidden: true }] },
  { title: "Decode Ways", topic: "Strings", difficulty: "MEDIUM", points: 200, description: "A message containing letters A-Z can be encoded using '1' -> 'A', '2' -> 'B', ..., '26' -> 'Z'. Given a string `s` of digits, return the number of ways to decode it.", constraints: "1 <= s.length <= 100\ns contains only digits", testCases: [{ input: "12", output: "2", isHidden: false }, { input: "226", output: "3", isHidden: false }, { input: "06", output: "0", isHidden: true }] },
  // Linked Lists (3)
  { title: "Palindrome Linked List", topic: "Linked Lists", difficulty: "EASY", points: 100, description: "Given the head of a singly linked list, return true if it is a palindrome.", constraints: "Number of nodes in range [1, 10^5]\n0 <= Node.val <= 9", testCases: [{ input: "[1,2,2,1]", output: "true", isHidden: false }, { input: "[1,2]", output: "false", isHidden: false }, { input: "[1]", output: "true", isHidden: true }] },
  { title: "Intersection of Two Linked Lists", topic: "Linked Lists", difficulty: "EASY", points: 100, description: "Given the heads of two singly linked-lists headA and headB, return the node at which the two lists intersect. If they do not intersect, return null.", constraints: "listA nodes in range [1, 3 * 10^4]\nlistB nodes in range [1, 3 * 10^4]", testCases: [{ input: "A=[4,1,8,4,5] B=[5,6,1,8,4,5]\nintersectVal=8", output: "8", isHidden: false }, { input: "A=[1,9,1,2,4] B=[3,2,4]\nintersectVal=2", output: "2", isHidden: false }, { input: "A=[2,6,4] B=[1,5]\nintersectVal=0", output: "null", isHidden: true }] },
  { title: "Sort List", topic: "Linked Lists", difficulty: "MEDIUM", points: 200, description: "Given the head of a linked list, return the list after sorting it in ascending order. Can you sort it in O(n log n) time and O(1) memory?", constraints: "Number of nodes in range [0, 5 * 10^4]\n-10^5 <= Node.val <= 10^5", testCases: [{ input: "[4,2,1,3]", output: "[1,2,3,4]", isHidden: false }, { input: "[-1,5,3,4,0]", output: "[-1,0,3,4,5]", isHidden: false }, { input: "[]", output: "[]", isHidden: true }] },
  // Trees (3)
  { title: "Symmetric Tree", topic: "Trees", difficulty: "EASY", points: 100, description: "Given the root of a binary tree, check whether it is a mirror of itself (i.e., symmetric around its center).", constraints: "Number of nodes in range [1, 1000]\n-100 <= Node.val <= 100", testCases: [{ input: "[1,2,2,3,4,4,3]", output: "true", isHidden: false }, { input: "[1,2,2,null,3,null,3]", output: "false", isHidden: false }, { input: "[1]", output: "true", isHidden: true }] },
  { title: "Construct Binary Tree from Preorder and Inorder Traversal", topic: "Trees", difficulty: "MEDIUM", points: 200, description: "Given two integer arrays `preorder` and `inorder`, construct and return the binary tree.", constraints: "1 <= preorder.length <= 3000\ninorder.length == preorder.length\nAll values are unique", testCases: [{ input: "[3,9,20,15,7]\n[9,3,15,20,7]", output: "[3,9,20,null,null,15,7]", isHidden: false }, { input: "[-1]\n[-1]", output: "[-1]", isHidden: false }, { input: "[1,2]\n[2,1]", output: "[1,2]", isHidden: true }] },
  { title: "Binary Tree Maximum Path Sum", topic: "Trees", difficulty: "HARD", points: 350, description: "A path in a binary tree is a sequence of nodes where each pair of adjacent nodes has an edge. Given the root, return the maximum path sum of any non-empty path.", constraints: "Number of nodes in range [1, 3 * 10^4]\n-1000 <= Node.val <= 1000", testCases: [{ input: "[1,2,3]", output: "6", isHidden: false }, { input: "[-10,9,20,null,null,15,7]", output: "42", isHidden: false }, { input: "[-3]", output: "-3", isHidden: true }] },
  // Graphs (3)
  { title: "Word Ladder", topic: "Graphs", difficulty: "HARD", points: 350, description: "Given two words `beginWord` and `endWord`, and a dictionary `wordList`, return the number of words in the shortest transformation sequence from beginWord to endWord, changing one letter at a time.", constraints: "1 <= beginWord.length <= 10\nendWord.length == beginWord.length\n1 <= wordList.length <= 5000", testCases: [{ input: "hit\ncog\n[hot,dot,dog,lot,log,cog]", output: "5", isHidden: false }, { input: "hit\ncog\n[hot,dot,dog,lot,log]", output: "0", isHidden: false }, { input: "a\nc\n[a,b,c]", output: "2", isHidden: true }] },
  { title: "Topological Sort", topic: "Graphs", difficulty: "MEDIUM", points: 200, description: "Given n tasks labeled 0 to n-1 and a list of dependency pairs, return a valid ordering of tasks. If no valid ordering exists, return an empty array.", constraints: "1 <= n <= 2000\n0 <= edges.length <= 5000", testCases: [{ input: "4\n[[1,0],[2,0],[3,1],[3,2]]", output: "[0,1,2,3]", isHidden: false }, { input: "2\n[[1,0]]", output: "[0,1]", isHidden: false }, { input: "2\n[[1,0],[0,1]]", output: "[]", isHidden: true }] },
  { title: "Network Delay Time", topic: "Graphs", difficulty: "MEDIUM", points: 200, description: "You are given a network of n nodes. Given times (directed edges with weights) and a source node k, return the minimum time for all nodes to receive a signal. Return -1 if impossible.", constraints: "1 <= k <= n <= 100\n1 <= times.length <= 6000", testCases: [{ input: "[[2,1,1],[2,3,1],[3,4,1]]\n4\n2", output: "2", isHidden: false }, { input: "[[1,2,1]]\n2\n1", output: "1", isHidden: false }, { input: "[[1,2,1]]\n2\n2", output: "-1", isHidden: true }] },
  // Dynamic Programming (3)
  { title: "Word Break", topic: "Dynamic Programming", difficulty: "MEDIUM", points: 200, description: "Given a string `s` and a dictionary of strings `wordDict`, return true if s can be segmented into a space-separated sequence of one or more dictionary words.", constraints: "1 <= s.length <= 300\n1 <= wordDict.length <= 1000", testCases: [{ input: "leetcode\n[leet,code]", output: "true", isHidden: false }, { input: "applepenapple\n[apple,pen]", output: "true", isHidden: false }, { input: "catsandog\n[cats,dog,sand,and,cat]", output: "false", isHidden: true }] },
  { title: "Unique Paths", topic: "Dynamic Programming", difficulty: "MEDIUM", points: 200, description: "A robot is on an m x n grid, starting at top-left. It can only move right or down. How many unique paths are there to the bottom-right corner?", constraints: "1 <= m, n <= 100", testCases: [{ input: "3\n7", output: "28", isHidden: false }, { input: "3\n2", output: "3", isHidden: false }, { input: "1\n1", output: "1", isHidden: true }] },
  { title: "Edit Distance", topic: "Dynamic Programming", difficulty: "MEDIUM", points: 200, description: "Given two strings `word1` and `word2`, return the minimum number of operations (insert, delete, replace) to convert word1 to word2.", constraints: "0 <= word1.length, word2.length <= 500", testCases: [{ input: "horse\nros", output: "3", isHidden: false }, { input: "intention\nexecution", output: "5", isHidden: false }, { input: "\na", output: "1", isHidden: true }] },
  // Backtracking (2)
  { title: "N-Queens", topic: "Backtracking", difficulty: "HARD", points: 350, description: "Place n queens on an n×n chessboard such that no two queens threaten each other. Return all distinct solutions.", constraints: "1 <= n <= 9", testCases: [{ input: "4", output: '[[".Q..","...Q","Q...","..Q."],["..Q.","Q...","...Q",".Q.."]]', isHidden: false }, { input: "1", output: '[["Q"]]', isHidden: false }, { input: "2", output: "[]", isHidden: true }] },
  { title: "Combination Sum", topic: "Backtracking", difficulty: "MEDIUM", points: 200, description: "Given an array of distinct integers `candidates` and a target `target`, return a list of all unique combinations of candidates where the chosen numbers sum to target. You may use the same number unlimited times.", constraints: "1 <= candidates.length <= 30\n2 <= candidates[i] <= 40\n1 <= target <= 40", testCases: [{ input: "[2,3,6,7]\n7", output: "[[2,2,3],[7]]", isHidden: false }, { input: "[2,3,5]\n8", output: "[[2,2,2,2],[2,3,3],[3,5]]", isHidden: false }, { input: "[2]\n1", output: "[]", isHidden: true }] },
  // Math (2)
  { title: "Happy Number", topic: "Math", difficulty: "EASY", points: 100, description: "Write an algorithm to determine if a number n is happy. A happy number is defined by the process of replacing the number by the sum of the squares of its digits, repeating until the number equals 1 or loops endlessly.", constraints: "1 <= n <= 2^31 - 1", testCases: [{ input: "19", output: "true", isHidden: false }, { input: "2", output: "false", isHidden: false }, { input: "7", output: "true", isHidden: true }] },
  { title: "Pow(x, n)", topic: "Math", difficulty: "MEDIUM", points: 200, description: "Implement pow(x, n), which calculates x raised to the power n.", constraints: "-100.0 < x < 100.0\n-2^31 <= n <= 2^31 - 1\nEither x != 0 or n > 0", testCases: [{ input: "2.00000\n10", output: "1024.00000", isHidden: false }, { input: "2.10000\n3", output: "9.26100", isHidden: false }, { input: "2.00000\n-2", output: "0.25000", isHidden: true }] },
];

async function main() {
  console.log("🧩  [Batch 2] Seeding 25 additional problems...\n");
  for (const p of problems) {
    await prisma.problem.create({
      data: { title: p.title, description: p.description, difficulty: p.difficulty, topic: p.topic, points: p.points, constraints: p.constraints, testCases: { create: p.testCases } },
    });
    console.log(`   ✅ ${p.title} [${p.topic}]`);
  }
  console.log(`\n🎉  Batch 2 complete! ${problems.length} problems added.\n`);
}

main()
  .catch((e) => { console.error("❌ Failed:", e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
