import "dotenv/config";
import { Pool } from "pg";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client.js";

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

type P = { title: string; topic: string; difficulty: string; points: number; description: string; constraints: string; testCases: { input: string; output: string; isHidden: boolean }[] };

const problems: P[] = [
  // Arrays (3)
  { title: "Kth Largest Element in an Array", topic: "Arrays", difficulty: "MEDIUM", points: 200, description: "Given an integer array `nums` and an integer `k`, return the kth largest element. You must solve it in O(n) average time.", constraints: "1 <= k <= nums.length <= 10^5\n-10^4 <= nums[i] <= 10^4", testCases: [{ input: "[3,2,1,5,6,4]\n2", output: "5", isHidden: false }, { input: "[3,2,3,1,2,4,5,5,6]\n4", output: "4", isHidden: false }, { input: "[1]\n1", output: "1", isHidden: true }] },
  { title: "Subarray Sum Equals K", topic: "Arrays", difficulty: "MEDIUM", points: 200, description: "Given an array of integers `nums` and an integer `k`, return the total number of subarrays whose sum equals to k.", constraints: "1 <= nums.length <= 2 * 10^4\n-1000 <= nums[i] <= 1000", testCases: [{ input: "[1,1,1]\n2", output: "2", isHidden: false }, { input: "[1,2,3]\n3", output: "2", isHidden: false }, { input: "[1,-1,0]\n0", output: "3", isHidden: true }] },
  { title: "Sliding Window Maximum", topic: "Arrays", difficulty: "HARD", points: 350, description: "Given an array nums and a sliding window of size k moving from left to right, return the maximum value in each window position.", constraints: "1 <= nums.length <= 10^5\n-10^4 <= nums[i] <= 10^4\n1 <= k <= nums.length", testCases: [{ input: "[1,3,-1,-3,5,3,6,7]\n3", output: "[3,3,5,5,6,7]", isHidden: false }, { input: "[1]\n1", output: "[1]", isHidden: false }, { input: "[1,-1]\n1", output: "[1,-1]", isHidden: true }] },
  // Strings (3)
  { title: "Count and Say", topic: "Strings", difficulty: "MEDIUM", points: 200, description: "The count-and-say sequence is a sequence of digit strings defined by the recursive formula. countAndSay(1) = '1'. countAndSay(n) is the run-length encoding of countAndSay(n - 1).", constraints: "1 <= n <= 30", testCases: [{ input: "1", output: "1", isHidden: false }, { input: "4", output: "1211", isHidden: false }, { input: "5", output: "111221", isHidden: true }] },
  { title: "Longest Repeating Character Replacement", topic: "Strings", difficulty: "MEDIUM", points: 200, description: "Given a string `s` and an integer `k`, you can choose any character and change it to any other uppercase English character. You can perform this at most k times. Return the length of the longest substring containing the same letter.", constraints: "1 <= s.length <= 10^5\ns consists of uppercase English letters\n0 <= k <= s.length", testCases: [{ input: "ABAB\n2", output: "4", isHidden: false }, { input: "AABABBA\n1", output: "4", isHidden: false }, { input: "AAAA\n0", output: "4", isHidden: true }] },
  { title: "Distinct Subsequences", topic: "Strings", difficulty: "HARD", points: 350, description: "Given two strings s and t, return the number of distinct subsequences of s which equals t.", constraints: "1 <= s.length, t.length <= 1000", testCases: [{ input: "rabbbit\nrabbit", output: "3", isHidden: false }, { input: "babgbag\nbag", output: "5", isHidden: false }, { input: "a\na", output: "1", isHidden: true }] },
  // Linked Lists (3)
  { title: "Flatten a Multilevel Doubly Linked List", topic: "Linked Lists", difficulty: "MEDIUM", points: 200, description: "You are given a doubly linked list where nodes may have a child pointer to a separate doubly linked sub-list. Flatten the list so that all nodes appear in a single-level, doubly linked list.", constraints: "Number of nodes <= 1000\n1 <= Node.val <= 10^6", testCases: [{ input: "[1,2,3,4,5,6,null,null,null,7,8,9,10,null,null,11,12]", output: "[1,2,3,7,8,11,12,9,10,4,5,6]", isHidden: false }, { input: "[1,2,null,3]", output: "[1,3,2]", isHidden: false }, { input: "[]", output: "[]", isHidden: true }] },
  { title: "Rotate List", topic: "Linked Lists", difficulty: "MEDIUM", points: 200, description: "Given the head of a linked list, rotate the list to the right by k places.", constraints: "Number of nodes in range [0, 500]\n-100 <= Node.val <= 100\n0 <= k <= 2 * 10^9", testCases: [{ input: "[1,2,3,4,5]\n2", output: "[4,5,1,2,3]", isHidden: false }, { input: "[0,1,2]\n4", output: "[2,0,1]", isHidden: false }, { input: "[1]\n1", output: "[1]", isHidden: true }] },
  { title: "Reorder List", topic: "Linked Lists", difficulty: "MEDIUM", points: 200, description: "Given the head of a singly linked-list L0→L1→…→Ln-1→Ln, reorder it to L0→Ln→L1→Ln-1→L2→Ln-2→…", constraints: "Number of nodes in range [1, 5 * 10^4]\n1 <= Node.val <= 1000", testCases: [{ input: "[1,2,3,4]", output: "[1,4,2,3]", isHidden: false }, { input: "[1,2,3,4,5]", output: "[1,5,2,4,3]", isHidden: false }, { input: "[1]", output: "[1]", isHidden: true }] },
  // Trees (3)
  { title: "Diameter of Binary Tree", topic: "Trees", difficulty: "EASY", points: 100, description: "Given the root of a binary tree, return the length of the diameter of the tree. The diameter is the length of the longest path between any two nodes (may or may not pass through root).", constraints: "Number of nodes in range [1, 10^4]\n-100 <= Node.val <= 100", testCases: [{ input: "[1,2,3,4,5]", output: "3", isHidden: false }, { input: "[1,2]", output: "1", isHidden: false }, { input: "[1]", output: "0", isHidden: true }] },
  { title: "Same Tree", topic: "Trees", difficulty: "EASY", points: 100, description: "Given the roots of two binary trees p and q, check if they are the same or not. Two binary trees are the same if they are structurally identical and nodes have the same value.", constraints: "Number of nodes in range [0, 100]\n-10^4 <= Node.val <= 10^4", testCases: [{ input: "[1,2,3]\n[1,2,3]", output: "true", isHidden: false }, { input: "[1,2]\n[1,null,2]", output: "false", isHidden: false }, { input: "[]\n[]", output: "true", isHidden: true }] },
  { title: "Subtree of Another Tree", topic: "Trees", difficulty: "EASY", points: 100, description: "Given the roots of two binary trees root and subRoot, return true if there is a subtree of root with the same structure and node values of subRoot.", constraints: "Number of nodes in root in range [1, 2000]\nNumber of nodes in subRoot in range [1, 1000]", testCases: [{ input: "[3,4,5,1,2]\n[4,1,2]", output: "true", isHidden: false }, { input: "[3,4,5,1,2,null,null,null,null,0]\n[4,1,2]", output: "false", isHidden: false }, { input: "[1]\n[1]", output: "true", isHidden: true }] },
  // Graphs (2)
  { title: "Course Schedule II", topic: "Graphs", difficulty: "MEDIUM", points: 200, description: "There are n courses labeled 0 to n-1. Given prerequisites, return the ordering of courses you should take to finish all courses. If impossible, return an empty array.", constraints: "1 <= numCourses <= 2000\n0 <= prerequisites.length <= numCourses * (numCourses - 1)", testCases: [{ input: "4\n[[1,0],[2,0],[3,1],[3,2]]", output: "[0,2,1,3]", isHidden: false }, { input: "2\n[[1,0]]", output: "[0,1]", isHidden: false }, { input: "1\n[]", output: "[0]", isHidden: true }] },
  { title: "Minimum Spanning Tree", topic: "Graphs", difficulty: "MEDIUM", points: 200, description: "Given a connected undirected graph with n nodes and weighted edges, find the minimum spanning tree weight using Kruskal's or Prim's algorithm.", constraints: "1 <= n <= 5000\n1 <= edges.length <= 10^5", testCases: [{ input: "4\n[[0,1,1],[0,2,4],[1,2,2],[2,3,3]]", output: "6", isHidden: false }, { input: "3\n[[0,1,5],[1,2,3],[0,2,1]]", output: "4", isHidden: false }, { input: "2\n[[0,1,10]]", output: "10", isHidden: true }] },
  // Dynamic Programming (4)
  { title: "Jump Game", topic: "Dynamic Programming", difficulty: "MEDIUM", points: 200, description: "Given an integer array `nums` where each element is the max jump length from that position, return true if you can reach the last index.", constraints: "1 <= nums.length <= 10^4\n0 <= nums[i] <= 10^5", testCases: [{ input: "[2,3,1,1,4]", output: "true", isHidden: false }, { input: "[3,2,1,0,4]", output: "false", isHidden: false }, { input: "[0]", output: "true", isHidden: true }] },
  { title: "Partition Equal Subset Sum", topic: "Dynamic Programming", difficulty: "MEDIUM", points: 200, description: "Given an integer array `nums`, return true if you can partition the array into two subsets such that the sum of elements in both subsets is equal.", constraints: "1 <= nums.length <= 200\n1 <= nums[i] <= 100", testCases: [{ input: "[1,5,11,5]", output: "true", isHidden: false }, { input: "[1,2,3,5]", output: "false", isHidden: false }, { input: "[1,1]", output: "true", isHidden: true }] },
  { title: "Maximal Square", topic: "Dynamic Programming", difficulty: "MEDIUM", points: 200, description: "Given an m x n binary matrix filled with 0's and 1's, find the largest square containing only 1's and return its area.", constraints: "m == matrix.length\nn == matrix[i].length\n1 <= m, n <= 300", testCases: [{ input: '[["1","0","1","0","0"],["1","0","1","1","1"],["1","1","1","1","1"],["1","0","0","1","0"]]', output: "4", isHidden: false }, { input: '[["0","1"],["1","0"]]', output: "1", isHidden: false }, { input: '[["0"]]', output: "0", isHidden: true }] },
  { title: "Burst Balloons", topic: "Dynamic Programming", difficulty: "HARD", points: 350, description: "You are given n balloons with numbers on them. Bursting balloon i gives you nums[i-1] * nums[i] * nums[i+1] coins. Return the maximum coins you can collect by bursting all the balloons wisely.", constraints: "n == nums.length\n1 <= n <= 300\n0 <= nums[i] <= 100", testCases: [{ input: "[3,1,5,8]", output: "167", isHidden: false }, { input: "[1,5]", output: "10", isHidden: false }, { input: "[1]", output: "1", isHidden: true }] },
  // Backtracking (2)
  { title: "Palindrome Partitioning (Backtrack)", topic: "Backtracking", difficulty: "MEDIUM", points: 200, description: "Given a string s, partition s such that every substring of the partition is a palindrome. Return all possible palindrome partitioning of s using backtracking.", constraints: "1 <= s.length <= 16", testCases: [{ input: "aab", output: '[["a","a","b"],["aa","b"]]', isHidden: false }, { input: "a", output: '[["a"]]', isHidden: false }, { input: "aba", output: '[["a","b","a"],["aba"]]', isHidden: true }] },
  { title: "Restore IP Addresses", topic: "Backtracking", difficulty: "MEDIUM", points: 200, description: "Given a string s containing only digits, return all possible valid IP addresses that can be formed by inserting dots into s.", constraints: "1 <= s.length <= 20\ns consists of digits only.", testCases: [{ input: "25525511135", output: '["255.255.11.135","255.255.111.35"]', isHidden: false }, { input: "0000", output: '["0.0.0.0"]', isHidden: false }, { input: "101023", output: '["1.0.10.23","1.0.102.3","10.1.0.23","10.10.2.3","101.0.2.3"]', isHidden: true }] },
  // Math (2)
  { title: "Reverse Integer", topic: "Math", difficulty: "MEDIUM", points: 200, description: "Given a signed 32-bit integer x, return x with its digits reversed. If reversing x causes the value to go outside the signed 32-bit integer range [-2^31, 2^31 - 1], then return 0.", constraints: "-2^31 <= x <= 2^31 - 1", testCases: [{ input: "123", output: "321", isHidden: false }, { input: "-123", output: "-321", isHidden: false }, { input: "120", output: "21", isHidden: true }] },
  { title: "Trailing Zeroes in Factorial", topic: "Math", difficulty: "MEDIUM", points: 200, description: "Given an integer n, return the number of trailing zeroes in n!. Your solution should be in logarithmic time complexity.", constraints: "0 <= n <= 10^4", testCases: [{ input: "3", output: "0", isHidden: false }, { input: "5", output: "1", isHidden: false }, { input: "30", output: "7", isHidden: true }] },
];

async function main() {
  console.log("🧩  [Batch 4] Seeding 25 additional problems...\n");
  for (const p of problems) {
    await prisma.problem.create({
      data: { title: p.title, description: p.description, difficulty: p.difficulty, topic: p.topic, points: p.points, constraints: p.constraints, testCases: { create: p.testCases } },
    });
    console.log(`   ✅ ${p.title} [${p.topic}]`);
  }
  console.log(`\n🎉  Batch 4 complete! ${problems.length} problems added.\n`);
}

main()
  .catch((e) => { console.error("❌ Failed:", e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
