import "dotenv/config";
import { Pool } from "pg";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client.js";

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

type P = { title: string; topic: string; difficulty: string; points: number; description: string; constraints: string; testCases: { input: string; output: string; isHidden: boolean }[] };

const problems: P[] = [
  // Arrays (3)
  { title: "Remove Duplicates from Sorted Array", topic: "Arrays", difficulty: "EASY", points: 100, description: "Given an integer array `nums` sorted in non-decreasing order, remove the duplicates in-place such that each unique element appears only once. Return the number of unique elements.", constraints: "1 <= nums.length <= 3 * 10^4\n-100 <= nums[i] <= 100", testCases: [{ input: "[1,1,2]", output: "2", isHidden: false }, { input: "[0,0,1,1,1,2,2,3,3,4]", output: "5", isHidden: false }, { input: "[1]", output: "1", isHidden: true }] },
  { title: "Rotate Array", topic: "Arrays", difficulty: "MEDIUM", points: 200, description: "Given an integer array `nums`, rotate the array to the right by `k` steps.", constraints: "1 <= nums.length <= 10^5\n-2^31 <= nums[i] <= 2^31 - 1\n0 <= k <= 10^5", testCases: [{ input: "[1,2,3,4,5,6,7]\n3", output: "[5,6,7,1,2,3,4]", isHidden: false }, { input: "[-1,-100,3,99]\n2", output: "[3,99,-1,-100]", isHidden: false }, { input: "[1,2]\n3", output: "[2,1]", isHidden: true }] },
  { title: "First Missing Positive", topic: "Arrays", difficulty: "HARD", points: 350, description: "Given an unsorted integer array `nums`, return the smallest missing positive integer. You must implement an algorithm that runs in O(n) time and uses O(1) auxiliary space.", constraints: "1 <= nums.length <= 10^5\n-2^31 <= nums[i] <= 2^31 - 1", testCases: [{ input: "[1,2,0]", output: "3", isHidden: false }, { input: "[3,4,-1,1]", output: "2", isHidden: false }, { input: "[7,8,9,11,12]", output: "1", isHidden: true }] },
  // Strings (3)
  { title: "Reverse String", topic: "Strings", difficulty: "EASY", points: 100, description: "Write a function that reverses a string. The input string is given as an array of characters `s`. You must do this by modifying the input array in-place with O(1) extra memory.", constraints: "1 <= s.length <= 10^5\ns[i] is a printable ascii character.", testCases: [{ input: '["h","e","l","l","o"]', output: '["o","l","l","e","h"]', isHidden: false }, { input: '["H","a","n","n","a","h"]', output: '["h","a","n","n","a","H"]', isHidden: false }, { input: '["a"]', output: '["a"]', isHidden: true }] },
  { title: "String to Integer (atoi)", topic: "Strings", difficulty: "MEDIUM", points: 200, description: "Implement the `myAtoi(string s)` function, which converts a string to a 32-bit signed integer.", constraints: "0 <= s.length <= 200\ns consists of English letters, digits, ' ', '+', '-', and '.'", testCases: [{ input: "42", output: "42", isHidden: false }, { input: "   -42", output: "-42", isHidden: false }, { input: "4193 with words", output: "4193", isHidden: true }] },
  { title: "Longest Common Prefix", topic: "Strings", difficulty: "EASY", points: 100, description: "Write a function to find the longest common prefix string amongst an array of strings. If there is no common prefix, return an empty string.", constraints: "1 <= strs.length <= 200\n0 <= strs[i].length <= 200", testCases: [{ input: '["flower","flow","flight"]', output: "fl", isHidden: false }, { input: '["dog","racecar","car"]', output: "", isHidden: false }, { input: '["a"]', output: "a", isHidden: true }] },
  // Linked Lists (3)
  { title: "Remove Nth Node From End of List", topic: "Linked Lists", difficulty: "MEDIUM", points: 200, description: "Given the head of a linked list, remove the nth node from the end of the list and return its head.", constraints: "1 <= sz <= 30\n0 <= Node.val <= 100\n1 <= n <= sz", testCases: [{ input: "[1,2,3,4,5]\n2", output: "[1,2,3,5]", isHidden: false }, { input: "[1]\n1", output: "[]", isHidden: false }, { input: "[1,2]\n1", output: "[1]", isHidden: true }] },
  { title: "Linked List Cycle", topic: "Linked Lists", difficulty: "EASY", points: 100, description: "Given `head`, the head of a linked list, determine if the linked list has a cycle in it.", constraints: "Number of nodes in range [0, 10^4]\n-10^5 <= Node.val <= 10^5", testCases: [{ input: "[3,2,0,-4]\npos=1", output: "true", isHidden: false }, { input: "[1,2]\npos=0", output: "true", isHidden: false }, { input: "[1]\npos=-1", output: "false", isHidden: true }] },
  { title: "Add Two Numbers", topic: "Linked Lists", difficulty: "MEDIUM", points: 200, description: "You are given two non-empty linked lists representing two non-negative integers stored in reverse order. Add the two numbers and return the sum as a linked list.", constraints: "Number of nodes in each list is [1, 100]\n0 <= Node.val <= 9", testCases: [{ input: "[2,4,3]\n[5,6,4]", output: "[7,0,8]", isHidden: false }, { input: "[0]\n[0]", output: "[0]", isHidden: false }, { input: "[9,9,9]\n[1]", output: "[0,0,0,1]", isHidden: true }] },
  // Trees (4)
  { title: "Maximum Depth of Binary Tree", topic: "Trees", difficulty: "EASY", points: 100, description: "Given the root of a binary tree, return its maximum depth. A binary tree's maximum depth is the number of nodes along the longest path from the root node down to the farthest leaf node.", constraints: "Number of nodes in range [0, 10^4]\n-100 <= Node.val <= 100", testCases: [{ input: "[3,9,20,null,null,15,7]", output: "3", isHidden: false }, { input: "[1,null,2]", output: "2", isHidden: false }, { input: "[]", output: "0", isHidden: true }] },
  { title: "Validate Binary Search Tree", topic: "Trees", difficulty: "MEDIUM", points: 200, description: "Given the root of a binary tree, determine if it is a valid binary search tree (BST).", constraints: "Number of nodes in range [1, 10^4]\n-2^31 <= Node.val <= 2^31 - 1", testCases: [{ input: "[2,1,3]", output: "true", isHidden: false }, { input: "[5,1,4,null,null,3,6]", output: "false", isHidden: false }, { input: "[1]", output: "true", isHidden: true }] },
  { title: "Binary Tree Level Order Traversal", topic: "Trees", difficulty: "MEDIUM", points: 200, description: "Given the root of a binary tree, return the level order traversal of its nodes' values (i.e., from left to right, level by level).", constraints: "Number of nodes in range [0, 2000]\n-1000 <= Node.val <= 1000", testCases: [{ input: "[3,9,20,null,null,15,7]", output: "[[3],[9,20],[15,7]]", isHidden: false }, { input: "[1]", output: "[[1]]", isHidden: false }, { input: "[]", output: "[]", isHidden: true }] },
  { title: "Invert Binary Tree", topic: "Trees", difficulty: "EASY", points: 100, description: "Given the root of a binary tree, invert the tree, and return its root.", constraints: "Number of nodes in range [0, 100]\n-100 <= Node.val <= 100", testCases: [{ input: "[4,2,7,1,3,6,9]", output: "[4,7,2,9,6,3,1]", isHidden: false }, { input: "[2,1,3]", output: "[2,3,1]", isHidden: false }, { input: "[]", output: "[]", isHidden: true }] },
  // Graphs (3)
  { title: "Clone Graph", topic: "Graphs", difficulty: "MEDIUM", points: 200, description: "Given a reference of a node in a connected undirected graph, return a deep copy (clone) of the graph.", constraints: "Number of nodes in range [0, 100]\n1 <= Node.val <= 100\nNo repeated edges or self-loops", testCases: [{ input: "[[2,4],[1,3],[2,4],[1,3]]", output: "[[2,4],[1,3],[2,4],[1,3]]", isHidden: false }, { input: "[[]]", output: "[[]]", isHidden: false }, { input: "[]", output: "[]", isHidden: true }] },
  { title: "Pacific Atlantic Water Flow", topic: "Graphs", difficulty: "MEDIUM", points: 200, description: "Given an m x n matrix of heights, return a list of grid coordinates where water can flow to both the Pacific and Atlantic oceans.", constraints: "m == heights.length\nn == heights[r].length\n1 <= m, n <= 200", testCases: [{ input: "[[1,2,2,3,5],[3,2,3,4,4],[2,4,5,3,1],[6,7,1,4,5],[5,1,1,2,4]]", output: "[[0,4],[1,3],[1,4],[2,2],[3,0],[3,1],[4,0]]", isHidden: false }, { input: "[[1]]", output: "[[0,0]]", isHidden: false }, { input: "[[1,1],[1,1]]", output: "[[0,0],[0,1],[1,0],[1,1]]", isHidden: true }] },
  { title: "Graph Valid Tree", topic: "Graphs", difficulty: "MEDIUM", points: 200, description: "Given n nodes labeled from 0 to n-1 and a list of undirected edges, check whether these edges make up a valid tree.", constraints: "1 <= n <= 2000\n0 <= edges.length <= 5000", testCases: [{ input: "5\n[[0,1],[0,2],[0,3],[1,4]]", output: "true", isHidden: false }, { input: "5\n[[0,1],[1,2],[2,3],[1,3],[1,4]]", output: "false", isHidden: false }, { input: "1\n[]", output: "true", isHidden: true }] },
  // Dynamic Programming (3)
  { title: "Coin Change", topic: "Dynamic Programming", difficulty: "MEDIUM", points: 200, description: "Given an integer array `coins` representing coin denominations and an integer `amount`, return the fewest number of coins needed to make up that amount. If that amount cannot be made up, return -1.", constraints: "1 <= coins.length <= 12\n1 <= coins[i] <= 2^31 - 1\n0 <= amount <= 10^4", testCases: [{ input: "[1,5,10]\n11", output: "3", isHidden: false }, { input: "[2]\n3", output: "-1", isHidden: false }, { input: "[1]\n0", output: "0", isHidden: true }] },
  { title: "Longest Increasing Subsequence", topic: "Dynamic Programming", difficulty: "MEDIUM", points: 200, description: "Given an integer array `nums`, return the length of the longest strictly increasing subsequence.", constraints: "1 <= nums.length <= 2500\n-10^4 <= nums[i] <= 10^4", testCases: [{ input: "[10,9,2,5,3,7,101,18]", output: "4", isHidden: false }, { input: "[0,1,0,3,2,3]", output: "4", isHidden: false }, { input: "[7,7,7,7,7,7,7]", output: "1", isHidden: true }] },
  { title: "House Robber", topic: "Dynamic Programming", difficulty: "MEDIUM", points: 200, description: "You are a professional robber planning to rob houses along a street. Each house has a certain amount of money. Adjacent houses have security systems connected — you cannot rob two adjacent houses. Return the maximum amount of money you can rob.", constraints: "1 <= nums.length <= 100\n0 <= nums[i] <= 400", testCases: [{ input: "[1,2,3,1]", output: "4", isHidden: false }, { input: "[2,7,9,3,1]", output: "12", isHidden: false }, { input: "[2,1,1,2]", output: "4", isHidden: true }] },
  // Backtracking (3)
  { title: "Permutations", topic: "Backtracking", difficulty: "MEDIUM", points: 200, description: "Given an array `nums` of distinct integers, return all possible permutations. You can return the answer in any order.", constraints: "1 <= nums.length <= 6\n-10 <= nums[i] <= 10\nAll integers are unique.", testCases: [{ input: "[1,2,3]", output: "[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]", isHidden: false }, { input: "[0,1]", output: "[[0,1],[1,0]]", isHidden: false }, { input: "[1]", output: "[[1]]", isHidden: true }] },
  { title: "Subsets", topic: "Backtracking", difficulty: "MEDIUM", points: 200, description: "Given an integer array `nums` of unique elements, return all possible subsets (the power set). The solution set must not contain duplicate subsets.", constraints: "1 <= nums.length <= 10\n-10 <= nums[i] <= 10\nAll elements are unique.", testCases: [{ input: "[1,2,3]", output: "[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]", isHidden: false }, { input: "[0]", output: "[[],[0]]", isHidden: false }, { input: "[1,2]", output: "[[],[1],[2],[1,2]]", isHidden: true }] },
  { title: "Letter Combinations of a Phone Number", topic: "Backtracking", difficulty: "MEDIUM", points: 200, description: "Given a string containing digits from 2-9 inclusive, return all possible letter combinations the number could represent.", constraints: "0 <= digits.length <= 4\ndigits[i] is a digit in range ['2', '9'].", testCases: [{ input: "23", output: '["ad","ae","af","bd","be","bf","cd","ce","cf"]', isHidden: false }, { input: "", output: "[]", isHidden: false }, { input: "2", output: '["a","b","c"]', isHidden: true }] },
  // Math (3)
  { title: "Palindrome Number", topic: "Math", difficulty: "EASY", points: 100, description: "Given an integer `x`, return true if x is a palindrome, and false otherwise, without converting the integer to a string.", constraints: "-2^31 <= x <= 2^31 - 1", testCases: [{ input: "121", output: "true", isHidden: false }, { input: "-121", output: "false", isHidden: false }, { input: "10", output: "false", isHidden: true }] },
  { title: "Power of Three", topic: "Math", difficulty: "EASY", points: 100, description: "Given an integer `n`, return true if it is a power of three. Otherwise, return false.", constraints: "-2^31 <= n <= 2^31 - 1", testCases: [{ input: "27", output: "true", isHidden: false }, { input: "0", output: "false", isHidden: false }, { input: "9", output: "true", isHidden: true }] },
  { title: "Count Primes", topic: "Math", difficulty: "MEDIUM", points: 200, description: "Given an integer `n`, return the number of prime numbers that are strictly less than `n`.", constraints: "0 <= n <= 5 * 10^6", testCases: [{ input: "10", output: "4", isHidden: false }, { input: "0", output: "0", isHidden: false }, { input: "1", output: "0", isHidden: true }] },
];

async function main() {
  console.log("🧩  [Batch 1] Seeding 25 additional problems...\n");
  for (const p of problems) {
    await prisma.problem.create({
      data: {
        title: p.title,
        description: p.description,
        difficulty: p.difficulty,
        topic: p.topic,
        points: p.points,
        constraints: p.constraints,
        testCases: { create: p.testCases },
      },
    });
    console.log(`   ✅ ${p.title} [${p.topic}]`);
  }
  console.log(`\n🎉  Batch 1 complete! ${problems.length} problems added.\n`);
}

main()
  .catch((e) => { console.error("❌ Failed:", e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
