import "dotenv/config";
import { Pool } from "pg";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client.js";

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

type P = { title: string; topic: string; difficulty: string; points: number; description: string; constraints: string; testCases: { input: string; output: string; isHidden: boolean }[] };

const problems: P[] = [
  // Arrays (3)
  { title: "Merge Intervals", topic: "Arrays", difficulty: "MEDIUM", points: 200, description: "Given an array of intervals where intervals[i] = [starti, endi], merge all overlapping intervals, and return an array of the non-overlapping intervals.", constraints: "1 <= intervals.length <= 10^4\nintervals[i].length == 2", testCases: [{ input: "[[1,3],[2,6],[8,10],[15,18]]", output: "[[1,6],[8,10],[15,18]]", isHidden: false }, { input: "[[1,4],[4,5]]", output: "[[1,5]]", isHidden: false }, { input: "[[1,4],[0,4]]", output: "[[0,4]]", isHidden: true }] },
  { title: "Spiral Matrix", topic: "Arrays", difficulty: "MEDIUM", points: 200, description: "Given an m x n matrix, return all elements of the matrix in spiral order.", constraints: "m == matrix.length\nn == matrix[i].length\n1 <= m, n <= 10", testCases: [{ input: "[[1,2,3],[4,5,6],[7,8,9]]", output: "[1,2,3,6,9,8,7,4,5]", isHidden: false }, { input: "[[1,2,3,4],[5,6,7,8],[9,10,11,12]]", output: "[1,2,3,4,8,12,11,10,9,5,6,7]", isHidden: false }, { input: "[[1]]", output: "[1]", isHidden: true }] },
  { title: "Maximum Product Subarray", topic: "Arrays", difficulty: "MEDIUM", points: 200, description: "Given an integer array `nums`, find a subarray that has the largest product, and return the product.", constraints: "1 <= nums.length <= 2 * 10^4\n-10 <= nums[i] <= 10", testCases: [{ input: "[2,3,-2,4]", output: "6", isHidden: false }, { input: "[-2,0,-1]", output: "0", isHidden: false }, { input: "[-2,3,-4]", output: "24", isHidden: true }] },
  // Strings (3)
  { title: "Palindrome Partitioning", topic: "Strings", difficulty: "MEDIUM", points: 200, description: "Given a string s, partition s such that every substring of the partition is a palindrome. Return all possible palindrome partitioning of s.", constraints: "1 <= s.length <= 16\ns contains only lowercase English letters.", testCases: [{ input: "aab", output: '[["a","a","b"],["aa","b"]]', isHidden: false }, { input: "a", output: '[["a"]]', isHidden: false }, { input: "aba", output: '[["a","b","a"],["aba"]]', isHidden: true }] },
  { title: "Minimum Remove to Make Valid Parentheses", topic: "Strings", difficulty: "MEDIUM", points: 200, description: "Given a string s of '(' , ')' and lowercase English characters, remove the minimum number of parentheses to make the resulting string valid.", constraints: "1 <= s.length <= 10^5\ns[i] is '(', ')' or lowercase English letter.", testCases: [{ input: "lee(t(c)o)de)", output: "lee(t(c)o)de", isHidden: false }, { input: "a)b(c)d", output: "ab(c)d", isHidden: false }, { input: "))(( ", output: "", isHidden: true }] },
  { title: "Wildcard Matching", topic: "Strings", difficulty: "HARD", points: 350, description: "Given an input string `s` and a pattern `p`, implement wildcard pattern matching with support for '?' (matches any single character) and '*' (matches any sequence of characters including empty).", constraints: "0 <= s.length, p.length <= 2000", testCases: [{ input: "aa\na", output: "false", isHidden: false }, { input: "aa\n*", output: "true", isHidden: false }, { input: "cb\n?a", output: "false", isHidden: true }] },
  // Linked Lists (3)
  { title: "Swap Nodes in Pairs", topic: "Linked Lists", difficulty: "MEDIUM", points: 200, description: "Given a linked list, swap every two adjacent nodes and return its head. You must solve the problem without modifying the values.", constraints: "Number of nodes in range [0, 100]\n0 <= Node.val <= 100", testCases: [{ input: "[1,2,3,4]", output: "[2,1,4,3]", isHidden: false }, { input: "[]", output: "[]", isHidden: false }, { input: "[1]", output: "[1]", isHidden: true }] },
  { title: "Reverse Nodes in k-Group", topic: "Linked Lists", difficulty: "HARD", points: 350, description: "Given the head of a linked list, reverse the nodes of the list k at a time, and return the modified list.", constraints: "Number of nodes in range [1, 5000]\n1 <= k <= n", testCases: [{ input: "[1,2,3,4,5]\n2", output: "[2,1,4,3,5]", isHidden: false }, { input: "[1,2,3,4,5]\n3", output: "[3,2,1,4,5]", isHidden: false }, { input: "[1]\n1", output: "[1]", isHidden: true }] },
  { title: "Copy List with Random Pointer", topic: "Linked Lists", difficulty: "MEDIUM", points: 200, description: "A linked list has nodes with a next pointer and a random pointer which could point to any node or null. Construct a deep copy of the list.", constraints: "0 <= n <= 1000\n-10^4 <= Node.val <= 10^4", testCases: [{ input: "[[7,null],[13,0],[11,4],[10,2],[1,0]]", output: "[[7,null],[13,0],[11,4],[10,2],[1,0]]", isHidden: false }, { input: "[[1,1],[2,1]]", output: "[[1,1],[2,1]]", isHidden: false }, { input: "[[3,null],[3,0],[3,null]]", output: "[[3,null],[3,0],[3,null]]", isHidden: true }] },
  // Trees (3)
  { title: "Lowest Common Ancestor of a Binary Tree", topic: "Trees", difficulty: "MEDIUM", points: 200, description: "Given a binary tree, find the lowest common ancestor (LCA) of two given nodes p and q.", constraints: "Number of nodes in range [2, 10^5]\nAll Node.val are unique\np != q", testCases: [{ input: "[3,5,1,6,2,0,8,null,null,7,4]\np=5 q=1", output: "3", isHidden: false }, { input: "[3,5,1,6,2,0,8,null,null,7,4]\np=5 q=4", output: "5", isHidden: false }, { input: "[1,2]\np=1 q=2", output: "1", isHidden: true }] },
  { title: "Kth Smallest Element in a BST", topic: "Trees", difficulty: "MEDIUM", points: 200, description: "Given the root of a BST and an integer k, return the kth smallest value (1-indexed) of all the values of the nodes.", constraints: "Number of nodes in range [1, 10^4]\n1 <= k <= n", testCases: [{ input: "[3,1,4,null,2]\n1", output: "1", isHidden: false }, { input: "[5,3,6,2,4,null,null,1]\n3", output: "3", isHidden: false }, { input: "[1]\n1", output: "1", isHidden: true }] },
  { title: "Path Sum II", topic: "Trees", difficulty: "MEDIUM", points: 200, description: "Given the root of a binary tree and an integer targetSum, return all root-to-leaf paths where the sum of the node values equals targetSum.", constraints: "Number of nodes in range [0, 5000]\n-1000 <= Node.val <= 1000", testCases: [{ input: "[5,4,8,11,null,13,4,7,2,null,null,5,1]\n22", output: "[[5,4,11,2],[5,8,4,5]]", isHidden: false }, { input: "[1,2,3]\n5", output: "[]", isHidden: false }, { input: "[1,2]\n1", output: "[]", isHidden: true }] },
  // Graphs (3)
  { title: "Surrounded Regions", topic: "Graphs", difficulty: "MEDIUM", points: 200, description: "Given an m x n matrix board of 'X' and 'O', capture all regions that are 4-directionally surrounded by 'X'. Flip all 'O's into 'X's in captured regions.", constraints: "m == board.length\nn == board[i].length\n1 <= m, n <= 200", testCases: [{ input: '[["X","X","X","X"],["X","O","O","X"],["X","X","O","X"],["X","O","X","X"]]', output: '[["X","X","X","X"],["X","X","X","X"],["X","X","X","X"],["X","O","X","X"]]', isHidden: false }, { input: '[["X"]]', output: '[["X"]]', isHidden: false }, { input: '[["O","O"],["O","O"]]', output: '[["O","O"],["O","O"]]', isHidden: true }] },
  { title: "Shortest Path in Binary Matrix", topic: "Graphs", difficulty: "MEDIUM", points: 200, description: "Given an n x n binary matrix grid, return the length of the shortest clear path from top-left to bottom-right. A clear path consists of cells with value 0.", constraints: "n == grid.length\nn == grid[i].length\n1 <= n <= 100", testCases: [{ input: "[[0,1],[1,0]]", output: "2", isHidden: false }, { input: "[[0,0,0],[1,1,0],[1,1,0]]", output: "4", isHidden: false }, { input: "[[1,0,0],[1,1,0],[1,1,0]]", output: "-1", isHidden: true }] },
  { title: "Alien Dictionary", topic: "Graphs", difficulty: "HARD", points: 350, description: "There is a new alien language that uses English letters but in a different order. Given a list of strings sorted lexicographically by the rules of this new language, derive the order of letters.", constraints: "1 <= words.length <= 100\n1 <= words[i].length <= 100", testCases: [{ input: '["wrt","wrf","er","ett","rftt"]', output: "wertf", isHidden: false }, { input: '["z","x"]', output: "zx", isHidden: false }, { input: '["z","x","z"]', output: "", isHidden: true }] },
  // Dynamic Programming (3)
  { title: "Longest Common Subsequence", topic: "Dynamic Programming", difficulty: "MEDIUM", points: 200, description: "Given two strings text1 and text2, return the length of their longest common subsequence. If there is no common subsequence, return 0.", constraints: "1 <= text1.length, text2.length <= 1000", testCases: [{ input: "abcde\nace", output: "3", isHidden: false }, { input: "abc\nabc", output: "3", isHidden: false }, { input: "abc\ndef", output: "0", isHidden: true }] },
  { title: "Decode Ways II", topic: "Dynamic Programming", difficulty: "HARD", points: 350, description: "A message containing letters can be decoded using '1'->'A'...'26'->'Z'. In addition, '*' can represent any digit from '1' to '9'. Given a string, return the number of ways to decode it modulo 10^9 + 7.", constraints: "1 <= s.length <= 10^5\ns[i] is digit or '*'", testCases: [{ input: "*", output: "9", isHidden: false }, { input: "1*", output: "18", isHidden: false }, { input: "2*", output: "15", isHidden: true }] },
  { title: "Palindrome Partitioning II", topic: "Dynamic Programming", difficulty: "HARD", points: 350, description: "Given a string s, return the minimum cuts needed for a palindrome partitioning of s.", constraints: "1 <= s.length <= 2000\ns consists of lowercase English letters only", testCases: [{ input: "aab", output: "1", isHidden: false }, { input: "a", output: "0", isHidden: false }, { input: "ab", output: "1", isHidden: true }] },
  // Backtracking (2)
  { title: "Generate Parentheses", topic: "Backtracking", difficulty: "MEDIUM", points: 200, description: "Given n pairs of parentheses, write a function to generate all combinations of well-formed parentheses.", constraints: "1 <= n <= 8", testCases: [{ input: "3", output: '["((()))","(()())","(())()","()(())","()()()"]', isHidden: false }, { input: "1", output: '["()"]', isHidden: false }, { input: "2", output: '["(())","()()"]', isHidden: true }] },
  { title: "Sudoku Solver", topic: "Backtracking", difficulty: "HARD", points: 350, description: "Write a program to solve a Sudoku puzzle by filling the empty cells (represented by '.'). A valid solution must satisfy all Sudoku rules.", constraints: "board.length == 9\nboard[i].length == 9\nboard[i][j] is digit or '.'", testCases: [{ input: "Standard 9x9 puzzle", output: "Completed 9x9 grid", isHidden: false }, { input: "Easy puzzle", output: "Solved puzzle", isHidden: false }, { input: "Hard puzzle", output: "Solved puzzle", isHidden: true }] },
  // Math (2)
  { title: "Sqrt(x)", topic: "Math", difficulty: "EASY", points: 100, description: "Given a non-negative integer x, return the square root of x rounded down to the nearest integer. You must not use any built-in exponent function or operator.", constraints: "0 <= x <= 2^31 - 1", testCases: [{ input: "4", output: "2", isHidden: false }, { input: "8", output: "2", isHidden: false }, { input: "0", output: "0", isHidden: true }] },
  { title: "Integer to Roman", topic: "Math", difficulty: "MEDIUM", points: 200, description: "Given an integer, convert it to a Roman numeral.", constraints: "1 <= num <= 3999", testCases: [{ input: "3749", output: "MMMDCCXLIX", isHidden: false }, { input: "58", output: "LVIII", isHidden: false }, { input: "1994", output: "MCMXCIV", isHidden: true }] },
];

async function main() {
  console.log("🧩  [Batch 3] Seeding 25 additional problems...\n");
  for (const p of problems) {
    await prisma.problem.create({
      data: { title: p.title, description: p.description, difficulty: p.difficulty, topic: p.topic, points: p.points, constraints: p.constraints, testCases: { create: p.testCases } },
    });
    console.log(`   ✅ ${p.title} [${p.topic}]`);
  }
  console.log(`\n🎉  Batch 3 complete! ${problems.length} problems added.\n`);
}

main()
  .catch((e) => { console.error("❌ Failed:", e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
